'use strict';

/**
 * Centralized Application Constants & Enums
 */
const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  FACULTY: 'FACULTY',
  STUDENT: 'STUDENT',
});

const ACCOUNT_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
});

const EXAM_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SCHEDULED: 'SCHEDULED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  RESULT_SUBMITTED: 'RESULT_SUBMITTED',
  RESULT_PUBLISHED: 'RESULT_PUBLISHED',
  CANCELLED: 'CANCELLED',
});

const LIFECYCLE_STATUSES = Object.freeze([
  EXAM_STATUS.DRAFT,
  EXAM_STATUS.SCHEDULED,
  EXAM_STATUS.ONGOING,
  EXAM_STATUS.COMPLETED,
  EXAM_STATUS.CANCELLED,
]);

const VALID_EXAM_TRANSITIONS = Object.freeze({
  [EXAM_STATUS.DRAFT]: [EXAM_STATUS.SCHEDULED, EXAM_STATUS.CANCELLED],
  [EXAM_STATUS.SCHEDULED]: [EXAM_STATUS.ONGOING, EXAM_STATUS.CANCELLED],
  [EXAM_STATUS.ONGOING]: [EXAM_STATUS.COMPLETED, EXAM_STATUS.CANCELLED],
  [EXAM_STATUS.COMPLETED]: [],
  [EXAM_STATUS.CANCELLED]: [],
});

const EXAM_TYPE = Object.freeze({
  INTERNAL: 'INTERNAL',
  MODEL: 'MODEL',
  END_SEMESTER: 'END_SEMESTER',
  PRACTICAL: 'PRACTICAL',
  QUIZ: 'QUIZ',
  SUPPLEMENTARY: 'SUPPLEMENTARY',
});

const QUESTION_PAPER_VERIFICATION = Object.freeze({
  NOT_VERIFIED: 'NOT_VERIFIED',
  VERIFIED: 'VERIFIED',
  TAMPER_DETECTED: 'TAMPER_DETECTED',
});

const RESULT_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  VERIFIED: 'VERIFIED',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED',
});

const VALID_RESULT_TRANSITIONS = Object.freeze({
  [RESULT_STATUS.DRAFT]: [RESULT_STATUS.SUBMITTED],
  [RESULT_STATUS.SUBMITTED]: [RESULT_STATUS.UNDER_REVIEW],
  [RESULT_STATUS.UNDER_REVIEW]: [RESULT_STATUS.VERIFIED, RESULT_STATUS.REJECTED],
  [RESULT_STATUS.REJECTED]: [RESULT_STATUS.DRAFT],
  [RESULT_STATUS.VERIFIED]: [RESULT_STATUS.PUBLISHED],
  [RESULT_STATUS.PUBLISHED]: [],
});

const GRIEVANCE_CATEGORY = Object.freeze({
  MARKS_DISCREPANCY: 'MARKS_DISCREPANCY',
  RESULT_NOT_PUBLISHED: 'RESULT_NOT_PUBLISHED',
  QUESTION_PAPER_ISSUE: 'QUESTION_PAPER_ISSUE',
  EXAMINATION_CONDUCT: 'EXAMINATION_CONDUCT',
  EVALUATION_CONCERN: 'EVALUATION_CONCERN',
  TECHNICAL_PROBLEM: 'TECHNICAL_PROBLEM',
  OTHER: 'OTHER',
});

const GRIEVANCE_STATUS = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ADDITIONAL_INFORMATION_REQUIRED: 'ADDITIONAL_INFORMATION_REQUIRED',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
  CLOSED: 'CLOSED',
});

const BLOCKCHAIN_TX_STATUS = Object.freeze({
  PENDING: 'PENDING',
  COMMITTED: 'COMMITTED',
  FAILED: 'FAILED',
});

module.exports = {
  ROLES,
  ACCOUNT_STATUS,
  EXAM_STATUS,
  LIFECYCLE_STATUSES,
  VALID_EXAM_TRANSITIONS,
  EXAM_TYPE,
  QUESTION_PAPER_VERIFICATION,
  RESULT_STATUS,
  VALID_RESULT_TRANSITIONS,
  GRIEVANCE_CATEGORY,
  GRIEVANCE_STATUS,
  BLOCKCHAIN_TX_STATUS,
};
